apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devops-guinea-pig
  description: Spring Boot application deployed to EKS via ArgoCD
  annotations:
    github.com/project-slug: shaileshsapkalgit/devops-guinea-pig
  tags:
    - java
    - spring-boot
  links:
    - url: https://ap-south-1.console.aws.amazon.com/ecr/repositories/private/748754852456/devops-guinea-pig?region=ap-south-1
      title: ECR Repository
      icon: docker
spec:
  type: service
  lifecycle: production
  owner: guests