{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-guinea-pig.serviceAccountName" . }}
  labels:
    {{- include "devops-guinea-pig.labels" . | nindent 4 }}
  {{- end }}