replicaCount: 2

image:

  repository: 748754852456.dkr.ecr.ap-south-1.amazonaws.com/devops-guinea-pig    # account ID बदललं
  tag: "af96983"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

probes:
  liveness:
    type: httpGet
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    type: httpGet
    path: /health
    initialDelaySeconds: 20
    periodSeconds: 10

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: ""
  path: /devops-guinea-pig(/|$)(.*)

env: []

serviceAccount:
  create: true
  name: ""