name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: 748754852456.dkr.ecr.ap-south-1.amazonaws.com/devops-guinea-pig    # account ID बदललं
  EKS_CLUSTER_NAME: devops-guinea-pig-eks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }} .

      - name: Push image to ECR
        run: |
          docker push $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Update image tag in values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"${{ steps.vars.outputs.IMAGE_TAG }}\"|" helm/devops-guinea-pig/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/devops-guinea-pig/values.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.IMAGE_TAG }} [skip ci]"
          git push origin main